name: Build and Release YTMusicUltimate
on:
  workflow_dispatch:
    inputs: 
      ipa_url:
        description: "URL to the decrypted IPA file"
        default: ""
        required: true
        type: string

      display_name:
        description: "App Name (Optional)"
        default: "YouTube Music"
        required: true
        type: string

      bundle_id:
        description: "BundleID (Optional)"
        default: "com.google.ios.youtubemusic"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build YTMusicUltimate
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: main
          submodules: recursive

      - name: Hide Sensitive Inputs
        uses: levibostian/action-hide-sensitive-inputs@v1
        with:
          exclude_inputs: bundle_id,display_name

      - name: Download and Validate IPA
        run: |
          wget "${{ inputs.ipa_url }}" --quiet --no-verbose -O ytm.ipa
          file_type=$(file --mime-type -b ytm.ipa)
          if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
            echo "::error::Validation failed: The downloaded file is not a valid IPA. Detected type: $file_type."
            exit 1
          fi

      - name: Get YouTube Music Version
        run: |
          unzip -q ytm.ipa -d ytmextracted
          echo "YTM_VERSION=$(grep -A 1 '<key>CFBundleVersion</key>' ytmextracted/Payload/*.app/Info.plist | grep '<string>' | awk -F'[><]' '{print $3}')" >> $GITHUB_ENV
          rm -rf ytmextracted

      - name: Get Tweak Version
        run: |
          echo "YTMU_VERSION=$(grep '^Version:' main/control | awk '{print $2}')" >> $GITHUB_ENV

      - name: Install Dependencies
        run: brew install make ldid

      - name: Set PATH Environment Variables
        run: |
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
          echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV

      - name: Cache Theos
        id: theos
        uses: actions/cache@v4
        env:
          cache-name: theos_cache_344ee59_sdk18.6
        with:
          path: theos/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Setup Theos
        if: steps.theos.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          ref: 344ee5925df036dbd1312b783ad5a00d153c2445
          path: theos
          submodules: recursive

      - name: Download iOS SDK
        if: steps.theos.outputs.cache-hit != 'true'
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/Tonwalter888/iOS-SDKs.git
          cd iOS-SDKs
          git sparse-checkout set --no-cone iPhoneOS18.6.sdk
          git checkout
          mv *.sdk $THEOS/sdks

      - name: Install cyan
        run: pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip

      - name: Build Tweak for Sideloading
        run: |
          cd main
          make clean package DEBUG=0 FINALPACKAGE=1 SIDELOADING=1
          mv packages/*.deb ../ytmult.deb

      - name: Inject Tweak Into IPA
        run: cyan -i ytm.ipa -o YTMusicUltimate_${{ env.YTM_VERSION }}_${{ env.YTMU_VERSION }}.ipa -uwesf ytmult.deb -n "${{ inputs.display_name }}" -b ${{ inputs.bundle_id }}

      - name: Create a Draft Release
        uses: softprops/action-gh-release@v2.6.2
        with:
          tag_name: ytmu-ipa${{ github.run_number }}
          name: YTMusicUltimate_${{ env.YTM_VERSION }}_${{ env.YTMU_VERSION }} (${{ github.run_number }})
          files: YTMusicUltimate_${{ env.YTM_VERSION }}_${{ env.YTMU_VERSION }}.ipa
          draft: true

      - name: Job Summary - Build Complete
        run: echo -e '### 🛠️ Build YTMusicUltimate IPA Complete!' >> $GITHUB_STEP_SUMMARY

      - name: Job Summary - Output the Draft Release Link
        run: |
          echo -e "### 🚀 Draft Release\n\nDraft release has been created successfully! You can view your release here: https://github.com/${{ github.repository }}/releases" >> $GITHUB_STEP_SUMMARY

